### ISSUE TITLE
Create Youtube Commands

### ISSUE THREAD

**Issue by camcast3** [prosolis/music#19]
- [x] !like - adds a like for the current song. Merged in PR #26 
- [x] !song - lists the current playing song. Currently in PR #32 
- [x] !artist - displays social media info for the current playing artist Currently in PR #32
